/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF, GLTFLoader } from "three/examples/jsm/Addons.js";
type GLTFResult = GLTF & {
  nodes: {
    Mesh_knifeBlock: THREE.Mesh;
    Mesh_knifeBlock_1: THREE.Mesh;
    Mesh_cookingKnife: THREE.Mesh;
    Mesh_cookingKnife_1: THREE.Mesh;
    Mesh_cookingKnife_2: THREE.Mesh;
  };
  materials: {
    brown: THREE.MeshStandardMaterial;
    brownLight: THREE.MeshStandardMaterial;
    white: THREE.MeshStandardMaterial;
    greyLight: THREE.MeshStandardMaterial;
    brownDark: THREE.MeshStandardMaterial;
  };
};

export default function KnifeStand(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/knife-block/model.gltf"
  ) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh_knifeBlock.geometry}
        material={materials.brown}
      />
      <mesh
        geometry={nodes.Mesh_knifeBlock_1.geometry}
        material={materials.brownLight}
      />
      <group position={[-0.09, 0.33, 0.05]} rotation={[-Math.PI / 2, 0.88, 0]}>
        <mesh
          geometry={nodes.Mesh_cookingKnife.geometry}
          material={nodes.Mesh_cookingKnife.material}
        />
        <mesh
          geometry={nodes.Mesh_cookingKnife_1.geometry}
          material={nodes.Mesh_cookingKnife_1.material}
        />
        <mesh
          geometry={nodes.Mesh_cookingKnife_2.geometry}
          material={nodes.Mesh_cookingKnife_2.material}
        />
      </group>
      <group position={[-0.16, 0.25, 0.01]} rotation={[-Math.PI / 2, 0.88, 0]}>
        <mesh
          geometry={nodes.Mesh_cookingKnife.geometry}
          material={nodes.Mesh_cookingKnife.material}
        />
        <mesh
          geometry={nodes.Mesh_cookingKnife_1.geometry}
          material={nodes.Mesh_cookingKnife_1.material}
        />
        <mesh
          geometry={nodes.Mesh_cookingKnife_2.geometry}
          material={nodes.Mesh_cookingKnife_2.material}
        />
      </group>
      <group position={[-0.09, 0.33, -0.03]} rotation={[-Math.PI / 2, 0.88, 0]}>
        <mesh
          geometry={nodes.Mesh_cookingKnife.geometry}
          material={nodes.Mesh_cookingKnife.material}
        />
        <mesh
          geometry={nodes.Mesh_cookingKnife_1.geometry}
          material={nodes.Mesh_cookingKnife_1.material}
        />
        <mesh
          geometry={nodes.Mesh_cookingKnife_2.geometry}
          material={nodes.Mesh_cookingKnife_2.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload(
  "https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/knife-block/model.gltf"
);
